In [1]:
from rembg import remove
from PIL import Image
import numpy as np

# Cargar imagen y eliminar fondo
with open('cat_dog_100/train/dog/dog.10095.jpg', 'rb') as f:
    input_image = f.read()

output_image = remove(input_image)

# Guardar el resultado sin fondo
with open('perro_sin_fondo.png', 'wb') as f:
    f.write(output_image)

ModuleNotFoundError: No module named 'rembg'

In [37]:
import numpy as np
import cv2
imagen = cv2.imread('cat_dog_100/train/dog/dog.10089.jpg', 0)
h, bins = np.histogram (imagen, bins = 256, range = [0, 256])
q = np.median(imagen)

print(imagen)
segmentada = imagen
segmentada[imagen>q] = 255
print(segmentada)

          
cv2.imshow('dst',segmentada)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[191 186 156 ... 124 149 166]
 [175 169 153 ... 135 146 154]
 [156 148 154 ... 134 130 129]
 ...
 [188 171 155 ... 187 169 132]
 [116 133 156 ... 192 186 157]
 [116 138 161 ... 212 223 215]]
[[255 255 156 ... 124 149 255]
 [255 255 153 ... 135 146 154]
 [156 148 154 ... 134 130 129]
 ...
 [255 255 155 ... 255 255 132]
 [116 133 156 ... 255 255 157]
 [116 138 255 ... 255 255 255]]
